version:  '3'
services:
  mlflow:
      build:
        context: .
        dockerfile: Dockerfile
      command: ../run_server.sh
      restart: unless-stopped
      environment:
        - BACKEND_URI=sqlite:///mlflow.db
        - ARTIFACT_ROOT=s3://11team-hm/mlflow/
      env_file:
        - .env
      volumes:
        - data:/usr/src/app/myapp
      ports:
        - 9005:5000

  serving1:
      build:
        context: .
        dockerfile: Dockerfile
      command: ../run_serving.sh
      restart: unless-stopped
      depends_on:
        - mlflow
      environment:
        - MLFLOW_TRACKING_URI=http://mlflow:5000
        - MODEL_RUN_ID=ae09e64fe1b848988df1533842f422ac
      env_file:
        - .env
      ports:
        - 9006:5000
        
volumes:
  data: