FROM debian:stable-slim

WORKDIR /usr/src/app

COPY . .

RUN apt-get update && apt-get install -y \
    make build-essential libssl-dev zlib1g-dev libbz2-dev \
    libreadline-dev libsqlite3-dev wget curl llvm \
    libncurses5-dev xz-utils tk-dev \
    libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev git\
    && curl https://pyenv.run | bash \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

ENV HOME /root
ENV PYENV_ROOT $HOME/.pyenv
ENV PATH $PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH

RUN pyenv install 3.10.13 \
    && pyenv global 3.10.13 \
    && python -m pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

ENV MLFLOW_TRACKING_URI=http://mlflow:5000
ENV MODEL_RUN_ID=runid

WORKDIR ./myapp

EXPOSE 5000

CMD mlflow models serve -m runs:/${MODEL_RUN_ID}/model -p 5000 --host 0.0.0.0
