version:  '3'
services:
  mlflow:
      build:
        context: .
        dockerfile: Dockerfile
      restart: unless-stopped
      environment:
        - BACKEND_URI=sqlite:///mlflow.db
        - ARTIFACT_ROOT=s3://11team-hm/mlflow/
      env_file:
        - .env
      volumes:
        - data:/usr/src/app/myapp
      ports:
        - 9005:5000

  serve1:
      build:
        context: .
        dockerfile: Dockerfile_serving
      restart: unless-stopped
      depends_on:
        - mlflow
      environment:
        - MLFLOW_TRACKING_URI=http://mlflow:5000
        - MODEL_RUN_ID=77fda43e39a344269a64c429c268d068
      ports:
        - 9006:5000
        
volumes:
  data: